"""add features and billing_period to products

Revision ID: 7f7ff944034d
Revises: b2d4f6a8c0e1
Create Date: 2026-08-09

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7ff944034d'
down_revision = 'b2d4f6a8c0e1'
branch_labels = None
depends_on = None


def upgrade():
    # Hand-written (not autogenerated) — autogenerate picked up a lot of
    # pre-existing, unrelated schema drift in this database that isn't part
    # of this change, so only the two new columns are included here.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('billing_period', sa.String(length=16), nullable=True))


def downgrade():
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('billing_period')
        batch_op.drop_column('features')
