"""Pushes a Website Builder site's generated files to a GitHub repo.

Reuses the GitHub credential type that already exists for Automation
Studio (app/utils/credential_providers.py's "github" provider, stored
encrypted in AutomationCredential) rather than adding a second place to
paste a token -- one GitHub connection, usable from both places.

Uses the plain REST Contents API (no git binary, no local clone needed):
  1. Create the repo if it doesn't exist yet (or reuse website.github_repo).
  2. PUT each file's content (base64) via /repos/{owner}/{repo}/contents/{path}
     -- this endpoint creates OR updates a file in one call, using the
     current file's sha when it already exists so this is safe to call
     repeatedly ("push updates") without ever needing a local git checkout.
"""
import base64
import requests as _requests

API_BASE = "https://api.github.com"


def _headers(token):
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def get_admin_github_token():
    """Looks up the admin's saved GitHub credential (Automation Studio ->
    Credentials). Returns (token, error)."""
    from app.models.platform import AutomationCredential
    cred = AutomationCredential.query.filter_by(provider="github", active=True).first()
    if not cred:
        return None, ("No GitHub connection found. Add one in Admin -> Automation Studio -> "
                       "Credentials (provider: GitHub, a personal access token with 'repo' scope) "
                       "-- it's shared with Website Builder's GitHub push.")
    secret = cred.get_secret() or {}
    token = secret.get("token")
    if not token:
        return None, "The saved GitHub credential has no token in it -- reconnect it in Automation Studio -> Credentials."
    return token, None


def _create_or_get_repo(token, repo_name, private=True):
    """Returns (owner/repo full_name, error)."""
    resp = _requests.get(f"{API_BASE}/user", headers=_headers(token), timeout=15)
    if resp.status_code != 200:
        return None, f"GitHub rejected the token (HTTP {resp.status_code}): {resp.text[:300]}"
    login = resp.json().get("login")

    # Does it already exist under this account?
    check = _requests.get(f"{API_BASE}/repos/{login}/{repo_name}", headers=_headers(token), timeout=15)
    if check.status_code == 200:
        return check.json()["full_name"], None

    create = _requests.post(
        f"{API_BASE}/user/repos", headers=_headers(token),
        json={"name": repo_name, "private": private, "auto_init": True,
              "description": "Generated by Bazillin Website Builder"},
        timeout=20,
    )
    if create.status_code not in (200, 201):
        return None, f"Couldn't create the GitHub repo (HTTP {create.status_code}): {create.text[:300]}"
    return create.json()["full_name"], None


def _put_file(token, full_repo, path, content):
    url = f"{API_BASE}/repos/{full_repo}/contents/{path}"
    existing = _requests.get(url, headers=_headers(token), timeout=15)
    sha = existing.json().get("sha") if existing.status_code == 200 else None
    body = {
        "message": f"Update {path} via Website Builder",
        "content": base64.b64encode((content or "").encode("utf-8")).decode("ascii"),
    }
    if sha:
        body["sha"] = sha
    resp = _requests.put(url, headers=_headers(token), json=body, timeout=20)
    if resp.status_code not in (200, 201):
        return f"Couldn't write {path} (HTTP {resp.status_code}): {resp.text[:300]}"
    return None


def push_website(website):
    """Pushes every page's html/css/js as real files (one folder per page)
    plus a top-level README. Returns (repo_url, error)."""
    token, err = get_admin_github_token()
    if err:
        return None, err

    if website.github_repo:
        full_repo = website.github_repo
    else:
        import re
        repo_name = re.sub(r"[^a-zA-Z0-9-]+", "-", website.slug or website.title or "website").strip("-").lower() or "website"
        full_repo, err = _create_or_get_repo(token, repo_name)
        if err:
            return None, err

    pages = website.pages or []
    readme = f"# {website.title}\n\nGenerated with Bazillin Website Builder.\n\nPages:\n"
    for p in pages:
        folder = (p.get("name") or "page").lower().replace(" ", "-")
        readme += f"- `{folder}/index.html`\n"
        for filename, content in (("index.html", p.get("html", "")),
                                   ("style.css", p.get("css", "")),
                                   ("script.js", p.get("js", ""))):
            err = _put_file(token, full_repo, f"{folder}/{filename}", content)
            if err:
                return None, err
    _put_file(token, full_repo, "README.md", readme)

    return f"https://github.com/{full_repo}", None
