"""
Automation Studio — App Integration Catalog
=============================================
This is a library of pre-configured node templates for the Automation
Studio visual builder. Every single entry here is just a *preset* for the
existing, fully-general `api_request` node (see app/utils/automation.py) —
method + URL + headers + body, all supporting {{context}} templating. No
new execution code is needed per integration: the graph engine already
knows how to run any REST call.

That's a deliberate choice over hand-writing a bespoke executor function
per app: a bespoke executor for 400 different services would mean 400
places that can silently drift from each provider's real API and 400
places to security-review. A data-driven catalog on top of one audited,
generic HTTP node is both safer and how these get added to going forward —
growing the library from here is adding an entry to this file, not writing
new backend code.

Every endpoint below is a real, stable, documented endpoint for that
provider as of writing (linked via `docs`). Auth is left as an obvious
placeholder (YOUR_X_TOKEN / YOUR_X_API_KEY) for the admin to fill in with
their own credential when they drag the node in — nothing here calls out
with a real key baked in.

To add more integrations: append an item to the relevant category's
"items" list (or add a new category). No other code changes needed —
the admin UI reads this catalog directly.
"""

CATALOG = [
    {
        "category": "Communication & Messaging",
        "icon": "💬",
        "items": [
            {
                "id": "gmail_send_email", "name": "Gmail — Send Email",
                "provider": "gmail", "group": "Message Actions",
                "method": "POST", "url": "https://gmail.googleapis.com/gmail/v1/users/me/messages/send",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"raw": "{{base64url_encoded_rfc2822_message}}"}',
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.messages/send",
            },
            {
                "id": "gmail_list_messages", "name": "Gmail — List Messages",
                "provider": "gmail", "group": "Message Actions",
                "method": "GET", "url": "https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=10",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.messages/list",
            },
            {
                "id": "gmail_search_messages", "name": "Gmail — Search Messages",
                "provider": "gmail", "group": "Message Actions",
                "method": "GET", "url": "https://gmail.googleapis.com/gmail/v1/users/me/messages?q={{search_query}}",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developers.google.com/gmail/api/guides/filtering",
            },
            {
                "id": "gmail_get_message", "name": "Gmail — Get Message",
                "provider": "gmail", "group": "Message Actions",
                "method": "GET", "url": "https://gmail.googleapis.com/gmail/v1/users/me/messages/{{message_id}}",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.messages/get",
            },
            {
                "id": "gmail_trash_message", "name": "Gmail — Delete Message (Trash)",
                "provider": "gmail", "group": "Message Actions",
                "method": "POST", "url": "https://gmail.googleapis.com/gmail/v1/users/me/messages/{{message_id}}/trash",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.messages/trash",
            },
            {
                "id": "gmail_add_label", "name": "Gmail — Add Label to Message",
                "provider": "gmail", "group": "Label Actions",
                "method": "POST", "url": "https://gmail.googleapis.com/gmail/v1/users/me/messages/{{message_id}}/modify",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"addLabelIds": ["{{label_id}}"]}',
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.messages/modify",
            },
            {
                "id": "gmail_remove_label", "name": "Gmail — Remove Label from Message",
                "provider": "gmail", "group": "Label Actions",
                "method": "POST", "url": "https://gmail.googleapis.com/gmail/v1/users/me/messages/{{message_id}}/modify",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"removeLabelIds": ["{{label_id}}"]}',
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.messages/modify",
            },
            {
                "id": "gmail_list_labels", "name": "Gmail — List Labels",
                "provider": "gmail", "group": "Label Actions",
                "method": "GET", "url": "https://gmail.googleapis.com/gmail/v1/users/me/labels",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.labels/list",
            },
            {
                "id": "gmail_create_draft", "name": "Gmail — Create Draft",
                "provider": "gmail", "group": "Draft Actions",
                "method": "POST", "url": "https://gmail.googleapis.com/gmail/v1/users/me/drafts",
                "headers": {"Authorization": "Bearer YOUR_GMAIL_OAUTH_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"message": {"raw": "{{base64url_encoded_rfc2822_message}}"}}',
                "docs": "https://developers.google.com/gmail/api/reference/rest/v1/users.drafts/create",
            },
            {
                "id": "slack_post_message", "name": "Slack — Post Message",
                "provider": "slack",
                "method": "POST", "url": "https://slack.com/api/chat.postMessage",
                "headers": {"Authorization": "Bearer YOUR_SLACK_BOT_TOKEN", "Content-Type": "application/json"},
                "body": '{"channel": "{{channel}}", "text": "{{message}}"}',
                "docs": "https://api.slack.com/methods/chat.postMessage",
            },
            {
                "id": "slack_upload_file", "name": "Slack — Upload File (external)",
                "provider": "slack",
                "method": "POST", "url": "https://slack.com/api/files.getUploadURLExternal",
                "headers": {"Authorization": "Bearer YOUR_SLACK_BOT_TOKEN", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "filename={{filename}}&length={{file_length}}",
                "docs": "https://api.slack.com/methods/files.getUploadURLExternal",
            },
            {
                "id": "slack_invite_user", "name": "Slack — Invite User to Channel",
                "provider": "slack",
                "method": "POST", "url": "https://slack.com/api/conversations.invite",
                "headers": {"Authorization": "Bearer YOUR_SLACK_BOT_TOKEN", "Content-Type": "application/json"},
                "body": '{"channel": "{{channel}}", "users": "{{user_id}}"}',
                "docs": "https://api.slack.com/methods/conversations.invite",
            },
            {
                "id": "slack_set_status", "name": "Slack — Set User Status",
                "provider": "slack",
                "method": "POST", "url": "https://slack.com/api/users.profile.set",
                "headers": {"Authorization": "Bearer YOUR_SLACK_USER_TOKEN", "Content-Type": "application/json"},
                "body": '{"profile": {"status_text": "{{status_text}}", "status_emoji": "{{status_emoji}}"}}',
                "docs": "https://api.slack.com/methods/users.profile.set",
            },
            {
                "id": "discord_webhook_message", "name": "Discord — Send Webhook Message",
                "method": "POST", "url": "YOUR_DISCORD_WEBHOOK_URL",
                "headers": {"Content-Type": "application/json"},
                "body": '{"content": "{{message}}"}',
                "docs": "https://discord.com/developers/docs/resources/webhook#execute-webhook",
            },
            {
                "id": "discord_bot_send_message", "name": "Discord — Bot Send Channel Message",
                "provider": "discord",
                "method": "POST", "url": "https://discord.com/api/v10/channels/{{channel_id}}/messages",
                "headers": {"Authorization": "Bot YOUR_DISCORD_BOT_TOKEN", "Content-Type": "application/json"},
                "body": '{"content": "{{message}}"}',
                "docs": "https://discord.com/developers/docs/resources/channel#create-message",
            },
            {
                "id": "telegram_send_message", "name": "Telegram — Send Message",
                "provider": "telegram",
                "method": "POST", "url": "https://api.telegram.org/botYOUR_TELEGRAM_BOT_TOKEN/sendMessage",
                "headers": {"Content-Type": "application/json"},
                "body": '{"chat_id": "{{chat_id}}", "text": "{{message}}"}',
                "docs": "https://core.telegram.org/bots/api#sendmessage",
            },
            {
                "id": "telegram_send_photo", "name": "Telegram — Send Photo",
                "provider": "telegram",
                "method": "POST", "url": "https://api.telegram.org/botYOUR_TELEGRAM_BOT_TOKEN/sendPhoto",
                "headers": {"Content-Type": "application/json"},
                "body": '{"chat_id": "{{chat_id}}", "photo": "{{photo_url}}", "caption": "{{caption}}"}',
                "docs": "https://core.telegram.org/bots/api#sendphoto",
            },
            {
                "id": "twilio_send_sms", "name": "Twilio — Send SMS",
                "provider": "twilio",
                "method": "POST", "url": "https://api.twilio.com/2010-04-01/Accounts/YOUR_TWILIO_ACCOUNT_SID/Messages.json",
                "headers": {"Authorization": "Basic BASE64(YOUR_TWILIO_ACCOUNT_SID:YOUR_TWILIO_AUTH_TOKEN)", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "To={{to_number}}&From=YOUR_TWILIO_NUMBER&Body={{message}}",
                "docs": "https://www.twilio.com/docs/sms/api/message-resource#create-a-message-resource",
            },
            {
                "id": "twilio_send_whatsapp", "name": "Twilio — Send WhatsApp Message",
                "provider": "twilio",
                "method": "POST", "url": "https://api.twilio.com/2010-04-01/Accounts/YOUR_TWILIO_ACCOUNT_SID/Messages.json",
                "headers": {"Authorization": "Basic BASE64(YOUR_TWILIO_ACCOUNT_SID:YOUR_TWILIO_AUTH_TOKEN)", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "To=whatsapp:{{to_number}}&From=whatsapp:YOUR_TWILIO_WHATSAPP_NUMBER&Body={{message}}",
                "docs": "https://www.twilio.com/docs/whatsapp/api",
            },
            {
                "id": "sendgrid_send_email", "name": "SendGrid — Send Email",
                "provider": "sendgrid",
                "method": "POST", "url": "https://api.sendgrid.com/v3/mail/send",
                "headers": {"Authorization": "Bearer YOUR_SENDGRID_API_KEY", "Content-Type": "application/json"},
                "body": '{"personalizations": [{"to": [{"email": "{{to_email}}"}]}], "from": {"email": "YOUR_FROM_EMAIL"}, "subject": "{{subject}}", "content": [{"type": "text/html", "value": "{{body_html}}"}]}',
                "docs": "https://docs.sendgrid.com/api-reference/mail-send/mail-send",
            },
            {
                "id": "mailgun_send_email", "name": "Mailgun — Send Email",
                "method": "POST", "url": "https://api.mailgun.net/v3/YOUR_MAILGUN_DOMAIN/messages",
                "headers": {"Authorization": "Basic BASE64(api:YOUR_MAILGUN_API_KEY)", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "from=YOUR_FROM_EMAIL&to={{to_email}}&subject={{subject}}&html={{body_html}}",
                "docs": "https://documentation.mailgun.com/en/latest/api-sending.html#sending",
            },
            {
                "id": "postmark_send_email", "name": "Postmark — Send Email",
                "method": "POST", "url": "https://api.postmarkapp.com/email",
                "headers": {"X-Postmark-Server-Token": "YOUR_POSTMARK_SERVER_TOKEN", "Content-Type": "application/json"},
                "body": '{"From": "YOUR_FROM_EMAIL", "To": "{{to_email}}", "Subject": "{{subject}}", "HtmlBody": "{{body_html}}"}',
                "docs": "https://postmarkapp.com/developer/api/email-api",
            },
            {
                "id": "pushover_notify", "name": "Pushover — Send Push Notification",
                "method": "POST", "url": "https://api.pushover.net/1/messages.json",
                "headers": {"Content-Type": "application/x-www-form-urlencoded"},
                "body": "token=YOUR_PUSHOVER_APP_TOKEN&user=YOUR_PUSHOVER_USER_KEY&message={{message}}",
                "docs": "https://pushover.net/api",
            },
            {
                "id": "onesignal_push", "name": "OneSignal — Send Push Notification",
                "method": "POST", "url": "https://onesignal.com/api/v1/notifications",
                "headers": {"Authorization": "Basic YOUR_ONESIGNAL_REST_API_KEY", "Content-Type": "application/json"},
                "body": '{"app_id": "YOUR_ONESIGNAL_APP_ID", "included_segments": ["All"], "contents": {"en": "{{message}}"}}',
                "docs": "https://documentation.onesignal.com/reference/create-notification",
            },
            {
                "id": "msteams_webhook_message", "name": "Microsoft Teams — Send Webhook Message",
                "method": "POST", "url": "YOUR_TEAMS_INCOMING_WEBHOOK_URL",
                "headers": {"Content-Type": "application/json"},
                "body": '{"text": "{{message}}"}',
                "docs": "https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook",
            },
        ],
    },
    {
        "category": "CRM & Sales",
        "icon": "📇",
        "items": [
            {
                "id": "hubspot_create_contact", "name": "HubSpot — Create Contact",
                "provider": "hubspot",
                "method": "POST", "url": "https://api.hubapi.com/crm/v3/objects/contacts",
                "headers": {"Authorization": "Bearer YOUR_HUBSPOT_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"properties": {"email": "{{email}}", "firstname": "{{first_name}}", "lastname": "{{last_name}}"}}',
                "docs": "https://developers.hubspot.com/docs/api/crm/contacts",
            },
            {
                "id": "hubspot_create_deal", "name": "HubSpot — Create Deal",
                "provider": "hubspot",
                "method": "POST", "url": "https://api.hubapi.com/crm/v3/objects/deals",
                "headers": {"Authorization": "Bearer YOUR_HUBSPOT_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"properties": {"dealname": "{{deal_name}}", "amount": "{{amount}}", "pipeline": "default", "dealstage": "{{stage}}"}}',
                "docs": "https://developers.hubspot.com/docs/api/crm/deals",
            },
            {
                "id": "pipedrive_create_person", "name": "Pipedrive — Create Person",
                "method": "POST", "url": "https://YOUR_COMPANY.pipedrive.com/api/v1/persons?api_token=YOUR_PIPEDRIVE_API_TOKEN",
                "headers": {"Content-Type": "application/json"},
                "body": '{"name": "{{name}}", "email": ["{{email}}"]}',
                "docs": "https://developers.pipedrive.com/docs/api/v1/Persons#addPerson",
            },
            {
                "id": "pipedrive_create_deal", "name": "Pipedrive — Create Deal",
                "method": "POST", "url": "https://YOUR_COMPANY.pipedrive.com/api/v1/deals?api_token=YOUR_PIPEDRIVE_API_TOKEN",
                "headers": {"Content-Type": "application/json"},
                "body": '{"title": "{{title}}", "value": "{{value}}", "currency": "USD"}',
                "docs": "https://developers.pipedrive.com/docs/api/v1/Deals#addDeal",
            },
            {
                "id": "zoho_crm_create_lead", "name": "Zoho CRM — Create Lead",
                "method": "POST", "url": "https://www.zohoapis.com/crm/v3/Leads",
                "headers": {"Authorization": "Zoho-oauthtoken YOUR_ZOHO_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"data": [{"Last_Name": "{{last_name}}", "Email": "{{email}}", "Company": "{{company}}"}]}',
                "docs": "https://www.zoho.com/crm/developer/docs/api/v3/insert-records.html",
            },
            {
                "id": "salesforce_create_lead", "name": "Salesforce — Create Lead",
                "method": "POST", "url": "https://YOUR_INSTANCE.salesforce.com/services/data/v59.0/sobjects/Lead",
                "headers": {"Authorization": "Bearer YOUR_SALESFORCE_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"LastName": "{{last_name}}", "Company": "{{company}}", "Email": "{{email}}"}',
                "docs": "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_create.htm",
            },
            {
                "id": "close_create_lead", "name": "Close — Create Lead",
                "method": "POST", "url": "https://api.close.com/api/v1/lead/",
                "headers": {"Authorization": "Bearer YOUR_CLOSE_API_KEY", "Content-Type": "application/json"},
                "body": '{"name": "{{company}}", "contacts": [{"name": "{{name}}", "emails": [{"email": "{{email}}"}]}]}',
                "docs": "https://developer.close.com/resources/leads/",
            },
        ],
    },
    {
        "category": "Payments & Billing",
        "icon": "💳",
        "items": [
            {
                "id": "stripe_create_customer", "name": "Stripe — Create Customer",
                "provider": "stripe",
                "method": "POST", "url": "https://api.stripe.com/v1/customers",
                "headers": {"Authorization": "Bearer YOUR_STRIPE_SECRET_KEY", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "email={{email}}&name={{name}}",
                "docs": "https://docs.stripe.com/api/customers/create",
            },
            {
                "id": "stripe_create_charge", "name": "Stripe — Create Payment Intent",
                "provider": "stripe",
                "method": "POST", "url": "https://api.stripe.com/v1/payment_intents",
                "headers": {"Authorization": "Bearer YOUR_STRIPE_SECRET_KEY", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "amount={{amount_cents}}&currency=usd&customer={{customer_id}}",
                "docs": "https://docs.stripe.com/api/payment_intents/create",
            },
            {
                "id": "stripe_create_invoice", "name": "Stripe — Create Invoice",
                "provider": "stripe",
                "method": "POST", "url": "https://api.stripe.com/v1/invoices",
                "headers": {"Authorization": "Bearer YOUR_STRIPE_SECRET_KEY", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "customer={{customer_id}}",
                "docs": "https://docs.stripe.com/api/invoices/create",
            },
            {
                "id": "stripe_create_refund", "name": "Stripe — Create Refund",
                "provider": "stripe",
                "method": "POST", "url": "https://api.stripe.com/v1/refunds",
                "headers": {"Authorization": "Bearer YOUR_STRIPE_SECRET_KEY", "Content-Type": "application/x-www-form-urlencoded"},
                "body": "payment_intent={{payment_intent_id}}",
                "docs": "https://docs.stripe.com/api/refunds/create",
            },
            {
                "id": "paypal_create_order", "name": "PayPal — Create Order",
                "method": "POST", "url": "https://api-m.paypal.com/v2/checkout/orders",
                "headers": {"Authorization": "Bearer YOUR_PAYPAL_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"intent": "CAPTURE", "purchase_units": [{"amount": {"currency_code": "USD", "value": "{{amount}}"}}]}',
                "docs": "https://developer.paypal.com/docs/api/orders/v2/#orders_create",
            },
            {
                "id": "paystack_initialize_transaction", "name": "Paystack — Initialize Transaction",
                "method": "POST", "url": "https://api.paystack.co/transaction/initialize",
                "headers": {"Authorization": "Bearer YOUR_PAYSTACK_SECRET_KEY", "Content-Type": "application/json"},
                "body": '{"email": "{{email}}", "amount": "{{amount_kobo}}"}',
                "docs": "https://paystack.com/docs/api/transaction/#initialize",
            },
            {
                "id": "flutterwave_initiate_payment", "name": "Flutterwave — Initiate Payment",
                "method": "POST", "url": "https://api.flutterwave.com/v3/payments",
                "headers": {"Authorization": "Bearer YOUR_FLUTTERWAVE_SECRET_KEY", "Content-Type": "application/json"},
                "body": '{"tx_ref": "{{tx_ref}}", "amount": "{{amount}}", "currency": "NGN", "redirect_url": "{{redirect_url}}", "customer": {"email": "{{email}}"}}',
                "docs": "https://developer.flutterwave.com/docs/making-payments/standard/",
            },
            {
                "id": "razorpay_create_order", "name": "Razorpay — Create Order",
                "method": "POST", "url": "https://api.razorpay.com/v1/orders",
                "headers": {"Authorization": "Basic BASE64(YOUR_RAZORPAY_KEY_ID:YOUR_RAZORPAY_KEY_SECRET)", "Content-Type": "application/json"},
                "body": '{"amount": "{{amount_paise}}", "currency": "INR"}',
                "docs": "https://razorpay.com/docs/api/orders/create/",
            },
            {
                "id": "square_create_payment", "name": "Square — Create Payment",
                "method": "POST", "url": "https://connect.squareup.com/v2/payments",
                "headers": {"Authorization": "Bearer YOUR_SQUARE_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"source_id": "{{source_id}}", "idempotency_key": "{{idempotency_key}}", "amount_money": {"amount": {{amount_cents}}, "currency": "USD"}}',
                "docs": "https://developer.squareup.com/reference/square/payments-api/create-payment",
            },
        ],
    },
    {
        "category": "Productivity & Project Management",
        "icon": "🗂️",
        "items": [
            {
                "id": "trello_create_card", "name": "Trello — Create Card",
                "method": "POST", "url": "https://api.trello.com/1/cards?key=YOUR_TRELLO_KEY&token=YOUR_TRELLO_TOKEN&idList=YOUR_LIST_ID&name={{name}}",
                "headers": {},
                "body": "",
                "docs": "https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-cards-post",
            },
            {
                "id": "trello_update_card", "name": "Trello — Update Card",
                "method": "PUT", "url": "https://api.trello.com/1/cards/{{card_id}}?key=YOUR_TRELLO_KEY&token=YOUR_TRELLO_TOKEN",
                "headers": {},
                "body": "",
                "docs": "https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-cards-id-put",
            },
            {
                "id": "asana_create_task", "name": "Asana — Create Task",
                "method": "POST", "url": "https://app.asana.com/api/1.0/tasks",
                "headers": {"Authorization": "Bearer YOUR_ASANA_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"data": {"name": "{{name}}", "notes": "{{notes}}", "projects": ["YOUR_PROJECT_ID"]}}',
                "docs": "https://developers.asana.com/reference/createtask",
            },
            {
                "id": "asana_update_task", "name": "Asana — Complete Task",
                "method": "PUT", "url": "https://app.asana.com/api/1.0/tasks/{{task_id}}",
                "headers": {"Authorization": "Bearer YOUR_ASANA_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"data": {"completed": true}}',
                "docs": "https://developers.asana.com/reference/updatetask",
            },
            {
                "id": "notion_create_page", "name": "Notion — Create Page",
                "provider": "notion",
                "method": "POST", "url": "https://api.notion.com/v1/pages",
                "headers": {"Authorization": "Bearer YOUR_NOTION_INTEGRATION_TOKEN", "Notion-Version": "2022-06-28", "Content-Type": "application/json"},
                "body": '{"parent": {"database_id": "YOUR_DATABASE_ID"}, "properties": {"Name": {"title": [{"text": {"content": "{{title}}"}}]}}}',
                "docs": "https://developers.notion.com/reference/post-page",
            },
            {
                "id": "notion_query_database", "name": "Notion — Query Database",
                "provider": "notion",
                "method": "POST", "url": "https://api.notion.com/v1/databases/YOUR_DATABASE_ID/query",
                "headers": {"Authorization": "Bearer YOUR_NOTION_INTEGRATION_TOKEN", "Notion-Version": "2022-06-28", "Content-Type": "application/json"},
                "body": "{}",
                "docs": "https://developers.notion.com/reference/post-database-query",
            },
            {
                "id": "clickup_create_task", "name": "ClickUp — Create Task",
                "method": "POST", "url": "https://api.clickup.com/api/v2/list/YOUR_LIST_ID/task",
                "headers": {"Authorization": "YOUR_CLICKUP_API_TOKEN", "Content-Type": "application/json"},
                "body": '{"name": "{{name}}", "description": "{{description}}"}',
                "docs": "https://developer.clickup.com/reference/createtask",
            },
            {
                "id": "monday_create_item", "name": "Monday.com — Create Item",
                "method": "POST", "url": "https://api.monday.com/v2",
                "headers": {"Authorization": "YOUR_MONDAY_API_TOKEN", "Content-Type": "application/json"},
                "body": '{"query": "mutation { create_item (board_id: YOUR_BOARD_ID, item_name: \\"{{name}}\\") { id } }"}',
                "docs": "https://developer.monday.com/api-reference/reference/items#create-an-item",
            },
            {
                "id": "airtable_create_record", "name": "Airtable — Create Record",
                "provider": "airtable",
                "method": "POST", "url": "https://api.airtable.com/v0/YOUR_BASE_ID/YOUR_TABLE_NAME",
                "headers": {"Authorization": "Bearer YOUR_AIRTABLE_TOKEN", "Content-Type": "application/json"},
                "body": '{"fields": {"Name": "{{name}}"}}',
                "docs": "https://airtable.com/developers/web/api/create-records",
            },
            {
                "id": "airtable_list_records", "name": "Airtable — List Records",
                "provider": "airtable",
                "method": "GET", "url": "https://api.airtable.com/v0/YOUR_BASE_ID/YOUR_TABLE_NAME",
                "headers": {"Authorization": "Bearer YOUR_AIRTABLE_TOKEN"},
                "body": "",
                "docs": "https://airtable.com/developers/web/api/list-records",
            },
            {
                "id": "jira_create_issue", "name": "Jira — Create Issue",
                "method": "POST", "url": "https://YOUR_DOMAIN.atlassian.net/rest/api/3/issue",
                "headers": {"Authorization": "Basic BASE64(YOUR_EMAIL:YOUR_JIRA_API_TOKEN)", "Content-Type": "application/json"},
                "body": '{"fields": {"project": {"key": "YOUR_PROJECT_KEY"}, "summary": "{{summary}}", "issuetype": {"name": "Task"}}}',
                "docs": "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-post",
            },
            {
                "id": "linear_create_issue", "name": "Linear — Create Issue",
                "method": "POST", "url": "https://api.linear.app/graphql",
                "headers": {"Authorization": "YOUR_LINEAR_API_KEY", "Content-Type": "application/json"},
                "body": '{"query": "mutation { issueCreate(input: {title: \\"{{title}}\\", teamId: \\"YOUR_TEAM_ID\\"}) { success } }"}',
                "docs": "https://developers.linear.app/docs/graphql/working-with-the-graphql-api",
            },
            {
                "id": "todoist_create_task", "name": "Todoist — Create Task",
                "method": "POST", "url": "https://api.todoist.com/rest/v2/tasks",
                "headers": {"Authorization": "Bearer YOUR_TODOIST_API_TOKEN", "Content-Type": "application/json"},
                "body": '{"content": "{{content}}"}',
                "docs": "https://developer.todoist.com/rest/v2/#create-a-new-task",
            },
        ],
    },
    {
        "category": "Developer & Ops",
        "icon": "🛠️",
        "items": [
            {
                "id": "github_create_issue", "name": "GitHub — Create Issue",
                "provider": "github",
                "method": "POST", "url": "https://api.github.com/repos/YOUR_OWNER/YOUR_REPO/issues",
                "headers": {"Authorization": "Bearer YOUR_GITHUB_TOKEN", "Accept": "application/vnd.github+json"},
                "body": '{"title": "{{title}}", "body": "{{body}}"}',
                "docs": "https://docs.github.com/en/rest/issues/issues#create-an-issue",
            },
            {
                "id": "github_create_comment", "name": "GitHub — Comment on Issue",
                "provider": "github",
                "method": "POST", "url": "https://api.github.com/repos/YOUR_OWNER/YOUR_REPO/issues/{{issue_number}}/comments",
                "headers": {"Authorization": "Bearer YOUR_GITHUB_TOKEN", "Accept": "application/vnd.github+json"},
                "body": '{"body": "{{comment}}"}',
                "docs": "https://docs.github.com/en/rest/issues/comments#create-an-issue-comment",
            },
            {
                "id": "github_trigger_workflow", "name": "GitHub — Trigger Workflow Dispatch",
                "provider": "github",
                "method": "POST", "url": "https://api.github.com/repos/YOUR_OWNER/YOUR_REPO/actions/workflows/YOUR_WORKFLOW_FILE/dispatches",
                "headers": {"Authorization": "Bearer YOUR_GITHUB_TOKEN", "Accept": "application/vnd.github+json"},
                "body": '{"ref": "main"}',
                "docs": "https://docs.github.com/en/rest/actions/workflows#create-a-workflow-dispatch-event",
            },
            {
                "id": "gitlab_create_issue", "name": "GitLab — Create Issue",
                "method": "POST", "url": "https://gitlab.com/api/v4/projects/YOUR_PROJECT_ID/issues",
                "headers": {"PRIVATE-TOKEN": "YOUR_GITLAB_TOKEN"},
                "body": "title={{title}}",
                "docs": "https://docs.gitlab.com/ee/api/issues.html#new-issue",
            },
            {
                "id": "vercel_deploy_hook", "name": "Vercel — Trigger Deploy Hook",
                "method": "POST", "url": "YOUR_VERCEL_DEPLOY_HOOK_URL",
                "headers": {},
                "body": "",
                "docs": "https://vercel.com/docs/deployments/deploy-hooks",
            },
            {
                "id": "netlify_build_hook", "name": "Netlify — Trigger Build Hook",
                "method": "POST", "url": "YOUR_NETLIFY_BUILD_HOOK_URL",
                "headers": {},
                "body": "",
                "docs": "https://docs.netlify.com/configure-builds/build-hooks/",
            },
            {
                "id": "circleci_trigger_pipeline", "name": "CircleCI — Trigger Pipeline",
                "method": "POST", "url": "https://circleci.com/api/v2/project/YOUR_PROJECT_SLUG/pipeline",
                "headers": {"Circle-Token": "YOUR_CIRCLECI_TOKEN", "Content-Type": "application/json"},
                "body": '{"branch": "main"}',
                "docs": "https://circleci.com/docs/api/v2/index.html#operation/triggerPipeline",
            },
            {
                "id": "pagerduty_trigger_incident", "name": "PagerDuty — Trigger Incident",
                "method": "POST", "url": "https://events.pagerduty.com/v2/enqueue",
                "headers": {"Content-Type": "application/json"},
                "body": '{"routing_key": "YOUR_PAGERDUTY_INTEGRATION_KEY", "event_action": "trigger", "payload": {"summary": "{{summary}}", "source": "automation", "severity": "error"}}',
                "docs": "https://developer.pagerduty.com/docs/send-alert-event",
            },
            {
                "id": "sentry_create_issue_comment", "name": "Sentry — Create Issue Comment",
                "method": "POST", "url": "https://sentry.io/api/0/issues/{{issue_id}}/comments/",
                "headers": {"Authorization": "Bearer YOUR_SENTRY_AUTH_TOKEN", "Content-Type": "application/json"},
                "body": '{"text": "{{comment}}"}',
                "docs": "https://docs.sentry.io/api/events/create-a-new-comment/",
            },
        ],
    },
    {
        "category": "E-commerce",
        "icon": "🛒",
        "items": [
            {
                "id": "shopify_create_order", "name": "Shopify — Create Order",
                "method": "POST", "url": "https://YOUR_STORE.myshopify.com/admin/api/2024-01/orders.json",
                "headers": {"X-Shopify-Access-Token": "YOUR_SHOPIFY_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"order": {"line_items": [{"variant_id": "{{variant_id}}", "quantity": "{{quantity}}"}]}}',
                "docs": "https://shopify.dev/docs/api/admin-rest/latest/resources/order#post-orders",
            },
            {
                "id": "shopify_create_product", "name": "Shopify — Create Product",
                "method": "POST", "url": "https://YOUR_STORE.myshopify.com/admin/api/2024-01/products.json",
                "headers": {"X-Shopify-Access-Token": "YOUR_SHOPIFY_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"product": {"title": "{{title}}"}}',
                "docs": "https://shopify.dev/docs/api/admin-rest/latest/resources/product#post-products",
            },
            {
                "id": "woocommerce_create_order", "name": "WooCommerce — Create Order",
                "method": "POST", "url": "https://YOUR_STORE.com/wp-json/wc/v3/orders",
                "headers": {"Authorization": "Basic BASE64(YOUR_WC_CONSUMER_KEY:YOUR_WC_CONSUMER_SECRET)", "Content-Type": "application/json"},
                "body": '{"line_items": [{"product_id": "{{product_id}}", "quantity": "{{quantity}}"}]}',
                "docs": "https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order",
            },
            {
                "id": "bigcommerce_create_order", "name": "BigCommerce — Create Order",
                "method": "POST", "url": "https://api.bigcommerce.com/stores/YOUR_STORE_HASH/v2/orders",
                "headers": {"X-Auth-Token": "YOUR_BIGCOMMERCE_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": "{}",
                "docs": "https://developer.bigcommerce.com/docs/rest-management/orders",
            },
        ],
    },
    {
        "category": "Marketing & Email",
        "icon": "📣",
        "items": [
            {
                "id": "mailchimp_add_subscriber", "name": "Mailchimp — Add Subscriber",
                "method": "POST", "url": "https://YOUR_DC.api.mailchimp.com/3.0/lists/YOUR_LIST_ID/members",
                "headers": {"Authorization": "Bearer YOUR_MAILCHIMP_API_KEY", "Content-Type": "application/json"},
                "body": '{"email_address": "{{email}}", "status": "subscribed"}',
                "docs": "https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/",
            },
            {
                "id": "activecampaign_add_contact", "name": "ActiveCampaign — Add Contact",
                "method": "POST", "url": "https://YOUR_ACCOUNT.api-us1.com/api/3/contacts",
                "headers": {"Api-Token": "YOUR_ACTIVECAMPAIGN_API_TOKEN", "Content-Type": "application/json"},
                "body": '{"contact": {"email": "{{email}}", "firstName": "{{first_name}}"}}',
                "docs": "https://developers.activecampaign.com/reference/create-a-new-contact",
            },
            {
                "id": "convertkit_add_subscriber", "name": "ConvertKit — Add Subscriber to Form",
                "method": "POST", "url": "https://api.convertkit.com/v3/forms/YOUR_FORM_ID/subscribe",
                "headers": {"Content-Type": "application/json"},
                "body": '{"api_key": "YOUR_CONVERTKIT_API_KEY", "email": "{{email}}"}',
                "docs": "https://developers.convertkit.com/#add-subscriber-to-a-form",
            },
            {
                "id": "klaviyo_track_event", "name": "Klaviyo — Track Event",
                "method": "POST", "url": "https://a.klaviyo.com/api/events/",
                "headers": {"Authorization": "Klaviyo-API-Key YOUR_KLAVIYO_PRIVATE_KEY", "Content-Type": "application/json", "revision": "2024-02-15"},
                "body": '{"data": {"type": "event", "attributes": {"metric": {"name": "{{event_name}}"}, "profile": {"email": "{{email}}"}}}}',
                "docs": "https://developers.klaviyo.com/en/reference/create_event",
            },
            {
                "id": "brevo_send_email", "name": "Brevo (Sendinblue) — Send Transactional Email",
                "method": "POST", "url": "https://api.brevo.com/v3/smtp/email",
                "headers": {"api-key": "YOUR_BREVO_API_KEY", "Content-Type": "application/json"},
                "body": '{"to": [{"email": "{{to_email}}"}], "subject": "{{subject}}", "htmlContent": "{{body_html}}"}',
                "docs": "https://developers.brevo.com/reference/sendtransacemail",
            },
        ],
    },
    {
        "category": "Social Media",
        "icon": "📱",
        "items": [
            {
                "id": "twitter_post_tweet", "name": "X / Twitter — Post Tweet",
                "method": "POST", "url": "https://api.twitter.com/2/tweets",
                "headers": {"Authorization": "Bearer YOUR_TWITTER_BEARER_TOKEN", "Content-Type": "application/json"},
                "body": '{"text": "{{text}}"}',
                "docs": "https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets",
            },
            {
                "id": "facebook_page_post", "name": "Facebook — Post to Page",
                "method": "POST", "url": "https://graph.facebook.com/v19.0/YOUR_PAGE_ID/feed",
                "headers": {},
                "body": "message={{message}}&access_token=YOUR_FACEBOOK_PAGE_TOKEN",
                "docs": "https://developers.facebook.com/docs/pages-api/posts",
            },
            {
                "id": "instagram_publish_post", "name": "Instagram — Publish Media",
                "method": "POST", "url": "https://graph.facebook.com/v19.0/YOUR_IG_USER_ID/media",
                "headers": {},
                "body": "image_url={{image_url}}&caption={{caption}}&access_token=YOUR_INSTAGRAM_ACCESS_TOKEN",
                "docs": "https://developers.facebook.com/docs/instagram-api/guides/content-publishing",
            },
            {
                "id": "linkedin_share_post", "name": "LinkedIn — Share Post",
                "method": "POST", "url": "https://api.linkedin.com/v2/ugcPosts",
                "headers": {"Authorization": "Bearer YOUR_LINKEDIN_ACCESS_TOKEN", "Content-Type": "application/json", "X-Restli-Protocol-Version": "2.0.0"},
                "body": '{"author": "urn:li:person:YOUR_PERSON_ID", "lifecycleState": "PUBLISHED", "specificContent": {"com.linkedin.ugc.ShareContent": {"shareCommentary": {"text": "{{text}}"}, "shareMediaCategory": "NONE"}}, "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"}}',
                "docs": "https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/ugc-post-api",
            },
            {
                "id": "pinterest_create_pin", "name": "Pinterest — Create Pin",
                "method": "POST", "url": "https://api.pinterest.com/v5/pins",
                "headers": {"Authorization": "Bearer YOUR_PINTEREST_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"board_id": "YOUR_BOARD_ID", "media_source": {"source_type": "image_url", "url": "{{image_url}}"}}',
                "docs": "https://developers.pinterest.com/docs/api/v5/#operation/pins/create",
            },
            {
                "id": "youtube_update_video", "name": "YouTube — Update Video Metadata",
                "method": "PUT", "url": "https://www.googleapis.com/youtube/v3/videos?part=snippet",
                "headers": {"Authorization": "Bearer YOUR_YOUTUBE_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"id": "{{video_id}}", "snippet": {"title": "{{title}}", "categoryId": "22"}}',
                "docs": "https://developers.google.com/youtube/v3/docs/videos/update",
            },
        ],
    },
    {
        "category": "Cloud Storage & Files",
        "icon": "☁️",
        "items": [
            {
                "id": "google_drive_upload", "name": "Google Drive — Upload File (metadata)",
                "method": "POST", "url": "https://www.googleapis.com/upload/drive/v3/files?uploadType=media",
                "headers": {"Authorization": "Bearer YOUR_GOOGLE_ACCESS_TOKEN", "Content-Type": "application/octet-stream"},
                "body": "",
                "docs": "https://developers.google.com/drive/api/guides/manage-uploads",
            },
            {
                "id": "dropbox_upload_file", "name": "Dropbox — Upload File",
                "method": "POST", "url": "https://content.dropboxapi.com/2/files/upload",
                "headers": {"Authorization": "Bearer YOUR_DROPBOX_ACCESS_TOKEN", "Dropbox-API-Arg": '{"path": "/{{filename}}", "mode": "add"}', "Content-Type": "application/octet-stream"},
                "body": "",
                "docs": "https://www.dropbox.com/developers/documentation/http/documentation#files-upload",
            },
            {
                "id": "onedrive_upload_file", "name": "OneDrive — Upload File (small)",
                "method": "PUT", "url": "https://graph.microsoft.com/v1.0/me/drive/root:/{{filename}}:/content",
                "headers": {"Authorization": "Bearer YOUR_ONEDRIVE_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content",
            },
            {
                "id": "box_upload_file", "name": "Box — Upload File",
                "method": "POST", "url": "https://upload.box.com/api/2.0/files/content",
                "headers": {"Authorization": "Bearer YOUR_BOX_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developer.box.com/reference/post-files-content/",
            },
            {
                "id": "aws_s3_put_object", "name": "AWS S3 — Put Object (presigned URL)",
                "method": "PUT", "url": "YOUR_S3_PRESIGNED_URL",
                "headers": {"Content-Type": "application/octet-stream"},
                "body": "",
                "docs": "https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html",
            },
        ],
    },
    {
        "category": "Calendar & Scheduling",
        "icon": "📅",
        "items": [
            {
                "id": "google_calendar_create_event", "name": "Google Calendar — Create Event",
                "method": "POST", "url": "https://www.googleapis.com/calendar/v3/calendars/primary/events",
                "headers": {"Authorization": "Bearer YOUR_GOOGLE_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"summary": "{{title}}", "start": {"dateTime": "{{start_time}}"}, "end": {"dateTime": "{{end_time}}"}}',
                "docs": "https://developers.google.com/calendar/api/v3/reference/events/insert",
            },
            {
                "id": "outlook_calendar_create_event", "name": "Outlook Calendar — Create Event",
                "method": "POST", "url": "https://graph.microsoft.com/v1.0/me/events",
                "headers": {"Authorization": "Bearer YOUR_MS_GRAPH_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"subject": "{{title}}", "start": {"dateTime": "{{start_time}}", "timeZone": "UTC"}, "end": {"dateTime": "{{end_time}}", "timeZone": "UTC"}}',
                "docs": "https://learn.microsoft.com/en-us/graph/api/user-post-events",
            },
            {
                "id": "calendly_list_invitees", "name": "Calendly — List Event Invitees",
                "method": "GET", "url": "https://api.calendly.com/scheduled_events/{{event_uuid}}/invitees",
                "headers": {"Authorization": "Bearer YOUR_CALENDLY_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developer.calendly.com/api-docs/b3A6NTA5NTU4MDU-list-event-invitees",
            },
            {
                "id": "cal_com_create_booking", "name": "Cal.com — Create Booking",
                "method": "POST", "url": "https://api.cal.com/v1/bookings?apiKey=YOUR_CALCOM_API_KEY",
                "headers": {"Content-Type": "application/json"},
                "body": '{"eventTypeId": "{{event_type_id}}", "start": "{{start_time}}", "responses": {"name": "{{name}}", "email": "{{email}}"}}',
                "docs": "https://cal.com/docs/api-reference/v1/bookings/creates-a-new-booking",
            },
        ],
    },
    {
        "category": "Forms & Surveys",
        "icon": "📝",
        "items": [
            {
                "id": "typeform_get_responses", "name": "Typeform — Get Form Responses",
                "method": "GET", "url": "https://api.typeform.com/forms/YOUR_FORM_ID/responses",
                "headers": {"Authorization": "Bearer YOUR_TYPEFORM_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developer.typeform.com/responses/reference/retrieve-responses/",
            },
            {
                "id": "jotform_get_submissions", "name": "JotForm — Get Form Submissions",
                "method": "GET", "url": "https://api.jotform.com/form/YOUR_FORM_ID/submissions?apiKey=YOUR_JOTFORM_API_KEY",
                "headers": {},
                "body": "",
                "docs": "https://api.jotform.com/docs/#form-id-submissions",
            },
            {
                "id": "surveymonkey_get_responses", "name": "SurveyMonkey — Get Survey Responses",
                "method": "GET", "url": "https://api.surveymonkey.com/v3/surveys/YOUR_SURVEY_ID/responses/bulk",
                "headers": {"Authorization": "Bearer YOUR_SURVEYMONKEY_ACCESS_TOKEN"},
                "body": "",
                "docs": "https://developer.surveymonkey.com/api/v3/#api-endpoints-get-surveys-id-responses-bulk",
            },
        ],
    },
    {
        "category": "Support & Helpdesk",
        "icon": "🎧",
        "items": [
            {
                "id": "zendesk_create_ticket", "name": "Zendesk — Create Ticket",
                "method": "POST", "url": "https://YOUR_SUBDOMAIN.zendesk.com/api/v2/tickets.json",
                "headers": {"Authorization": "Basic BASE64(YOUR_EMAIL/token:YOUR_ZENDESK_API_TOKEN)", "Content-Type": "application/json"},
                "body": '{"ticket": {"subject": "{{subject}}", "comment": {"body": "{{message}}"}}}',
                "docs": "https://developer.zendesk.com/api-reference/ticketing/tickets/tickets/#create-ticket",
            },
            {
                "id": "intercom_create_conversation", "name": "Intercom — Create Conversation",
                "method": "POST", "url": "https://api.intercom.io/conversations",
                "headers": {"Authorization": "Bearer YOUR_INTERCOM_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"from": {"type": "user", "id": "{{user_id}}"}, "body": "{{message}}"}',
                "docs": "https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/createconversation",
            },
            {
                "id": "freshdesk_create_ticket", "name": "Freshdesk — Create Ticket",
                "method": "POST", "url": "https://YOUR_DOMAIN.freshdesk.com/api/v2/tickets",
                "headers": {"Authorization": "Basic BASE64(YOUR_FRESHDESK_API_KEY:X)", "Content-Type": "application/json"},
                "body": '{"subject": "{{subject}}", "description": "{{message}}", "email": "{{email}}", "priority": 1, "status": 2}',
                "docs": "https://developers.freshdesk.com/api/#create_ticket",
            },
            {
                "id": "helpscout_create_conversation", "name": "Help Scout — Create Conversation",
                "method": "POST", "url": "https://api.helpscout.net/v2/conversations",
                "headers": {"Authorization": "Bearer YOUR_HELPSCOUT_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"subject": "{{subject}}", "mailboxId": YOUR_MAILBOX_ID, "customer": {"email": "{{email}}"}, "threads": [{"type": "customer", "customer": {"email": "{{email}}"}, "text": "{{message}}"}]}',
                "docs": "https://developer.helpscout.com/mailbox-api/endpoints/conversations/create/",
            },
        ],
    },
    {
        "category": "AI & Machine Learning",
        "icon": "🤖",
        "items": [
            {
                "id": "openai_chat_completion", "name": "OpenAI — Chat Completion",
                "provider": "openai", "group": "Text Actions",
                "method": "POST", "url": "https://api.openai.com/v1/chat/completions",
                "headers": {"Authorization": "Bearer YOUR_OPENAI_API_KEY", "Content-Type": "application/json"},
                "body": '{"model": "gpt-4o-mini", "messages": [{"role": "user", "content": "{{prompt}}"}]}',
                "docs": "https://platform.openai.com/docs/api-reference/chat/create",
            },
            {
                "id": "openai_generate_image", "name": "OpenAI — Generate Image",
                "provider": "openai", "group": "Image Actions",
                "method": "POST", "url": "https://api.openai.com/v1/images/generations",
                "headers": {"Authorization": "Bearer YOUR_OPENAI_API_KEY", "Content-Type": "application/json"},
                "body": '{"model": "dall-e-3", "prompt": "{{prompt}}", "n": 1, "size": "1024x1024"}',
                "docs": "https://platform.openai.com/docs/api-reference/images/create",
            },
            {
                "id": "openai_text_to_speech", "name": "OpenAI — Text to Speech",
                "provider": "openai", "group": "Audio Actions",
                "method": "POST", "url": "https://api.openai.com/v1/audio/speech",
                "headers": {"Authorization": "Bearer YOUR_OPENAI_API_KEY", "Content-Type": "application/json"},
                "body": '{"model": "tts-1", "input": "{{text}}", "voice": "alloy"}',
                "docs": "https://platform.openai.com/docs/api-reference/audio/createSpeech",
            },
            {
                "id": "openai_create_embedding", "name": "OpenAI — Create Embedding",
                "provider": "openai", "group": "Embedding Actions",
                "method": "POST", "url": "https://api.openai.com/v1/embeddings",
                "headers": {"Authorization": "Bearer YOUR_OPENAI_API_KEY", "Content-Type": "application/json"},
                "body": '{"model": "text-embedding-3-small", "input": "{{text}}"}',
                "docs": "https://platform.openai.com/docs/api-reference/embeddings/create",
            },
            {
                "id": "anthropic_messages", "name": "Anthropic — Create Message",
                "provider": "anthropic", "group": "Text Actions",
                "method": "POST", "url": "https://api.anthropic.com/v1/messages",
                "headers": {"x-api-key": "YOUR_ANTHROPIC_API_KEY", "anthropic-version": "2023-06-01", "Content-Type": "application/json"},
                "body": '{"model": "claude-sonnet-4-6", "max_tokens": 1000, "messages": [{"role": "user", "content": "{{prompt}}"}]}',
                "docs": "https://docs.claude.com/en/api/messages",
            },
            {
                "id": "anthropic_analyze_image", "name": "Anthropic — Analyze Image",
                "provider": "anthropic", "group": "Image Actions",
                "method": "POST", "url": "https://api.anthropic.com/v1/messages",
                "headers": {"x-api-key": "YOUR_ANTHROPIC_API_KEY", "anthropic-version": "2023-06-01", "Content-Type": "application/json"},
                "body": '{"model": "claude-sonnet-4-6", "max_tokens": 1000, "messages": [{"role": "user", "content": [{"type": "image", "source": {"type": "base64", "media_type": "image/jpeg", "data": "{{image_base64}}"}}, {"type": "text", "text": "{{prompt}}"}]}]}',
                "docs": "https://docs.claude.com/en/docs/build-with-claude/vision",
            },
            {
                "id": "gemini_generate_content", "name": "Google Gemini — Generate Content",
                "provider": "google_gemini", "group": "Text Actions",
                "method": "POST", "url": "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=YOUR_GEMINI_API_KEY",
                "headers": {"Content-Type": "application/json"},
                "body": '{"contents": [{"parts": [{"text": "{{prompt}}"}]}]}',
                "docs": "https://ai.google.dev/api/generate-content",
            },
            {
                "id": "gemini_analyze_image", "name": "Google Gemini — Analyze Image",
                "provider": "google_gemini", "group": "Image Actions",
                "method": "POST", "url": "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=YOUR_GEMINI_API_KEY",
                "headers": {"Content-Type": "application/json"},
                "body": '{"contents": [{"parts": [{"inline_data": {"mime_type": "image/jpeg", "data": "{{image_base64}}"}}, {"text": "{{prompt}}"}]}]}',
                "docs": "https://ai.google.dev/gemini-api/docs/vision",
            },
            {
                "id": "gemini_embed_content", "name": "Google Gemini — Embed Content",
                "provider": "google_gemini", "group": "Embedding Actions",
                "method": "POST", "url": "https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:embedContent?key=YOUR_GEMINI_API_KEY",
                "headers": {"Content-Type": "application/json"},
                "body": '{"content": {"parts": [{"text": "{{text}}"}]}}',
                "docs": "https://ai.google.dev/api/embeddings",
            },
            {
                "id": "stability_generate_image", "name": "Stability AI — Generate Image",
                "provider": "stability_ai", "group": "Image Actions",
                "method": "POST", "url": "https://api.stability.ai/v2beta/stable-image/generate/core",
                "headers": {"Authorization": "Bearer YOUR_STABILITY_API_KEY", "Accept": "application/json"},
                "body": "prompt={{prompt}}",
                "docs": "https://platform.stability.ai/docs/api-reference#tag/Generate/paths/~1v2beta~1stable-image~1generate~1core/post",
            },
            {
                "id": "elevenlabs_text_to_speech", "name": "ElevenLabs — Text to Speech",
                "provider": "elevenlabs", "group": "Audio Actions",
                "method": "POST", "url": "https://api.elevenlabs.io/v1/text-to-speech/YOUR_VOICE_ID",
                "headers": {"xi-api-key": "YOUR_ELEVENLABS_API_KEY", "Content-Type": "application/json"},
                "body": '{"text": "{{text}}", "model_id": "eleven_monolingual_v1"}',
                "docs": "https://elevenlabs.io/docs/api-reference/text-to-speech",
            },
            {
                "id": "replicate_run_model", "name": "Replicate — Run Model Prediction",
                "provider": "replicate", "group": "Model Actions",
                "method": "POST", "url": "https://api.replicate.com/v1/predictions",
                "headers": {"Authorization": "Bearer YOUR_REPLICATE_API_TOKEN", "Content-Type": "application/json"},
                "body": '{"version": "YOUR_MODEL_VERSION_ID", "input": {"prompt": "{{prompt}}"}}',
                "docs": "https://replicate.com/docs/reference/http#predictions.create",
            },
        ],
    },
    {
        "category": "Analytics & Data",
        "icon": "📊",
        "items": [
            {
                "id": "google_analytics_send_event", "name": "Google Analytics 4 — Send Event",
                "method": "POST", "url": "https://www.google-analytics.com/mp/collect?measurement_id=YOUR_GA4_MEASUREMENT_ID&api_secret=YOUR_GA4_API_SECRET",
                "headers": {"Content-Type": "application/json"},
                "body": '{"client_id": "{{client_id}}", "events": [{"name": "{{event_name}}"}]}',
                "docs": "https://developers.google.com/analytics/devguides/collection/protocol/ga4",
            },
            {
                "id": "segment_track_event", "name": "Segment — Track Event",
                "method": "POST", "url": "https://api.segment.io/v1/track",
                "headers": {"Authorization": "Basic BASE64(YOUR_SEGMENT_WRITE_KEY:)", "Content-Type": "application/json"},
                "body": '{"userId": "{{user_id}}", "event": "{{event_name}}"}',
                "docs": "https://segment.com/docs/connections/sources/catalog/libraries/server/http-api/#track",
            },
            {
                "id": "mixpanel_track_event", "name": "Mixpanel — Track Event",
                "method": "POST", "url": "https://api.mixpanel.com/track",
                "headers": {"Authorization": "Basic BASE64(YOUR_MIXPANEL_API_SECRET:)", "Content-Type": "application/json"},
                "body": '[{"event": "{{event_name}}", "properties": {"token": "YOUR_MIXPANEL_TOKEN", "distinct_id": "{{user_id}}"}}]',
                "docs": "https://developer.mixpanel.com/reference/track-event",
            },
        ],
    },
    {
        "category": "Utility & Generic",
        "icon": "🧰",
        "items": [
            {
                "id": "http_get", "name": "Generic — HTTP GET Request",
                "method": "GET", "url": "https://api.example.com/{{path}}",
                "headers": {}, "body": "",
                "docs": None,
            },
            {
                "id": "http_post_json", "name": "Generic — HTTP POST (JSON)",
                "method": "POST", "url": "https://api.example.com/{{path}}",
                "headers": {"Content-Type": "application/json"}, "body": '{"key": "{{value}}"}',
                "docs": None,
            },
            {
                "id": "http_put_json", "name": "Generic — HTTP PUT (JSON)",
                "method": "PUT", "url": "https://api.example.com/{{path}}",
                "headers": {"Content-Type": "application/json"}, "body": '{"key": "{{value}}"}',
                "docs": None,
            },
            {
                "id": "http_delete", "name": "Generic — HTTP DELETE",
                "method": "DELETE", "url": "https://api.example.com/{{path}}",
                "headers": {}, "body": "",
                "docs": None,
            },
            {
                "id": "bitly_shorten_url", "name": "Bitly — Shorten URL",
                "method": "POST", "url": "https://api-ssl.bitly.com/v4/shorten",
                "headers": {"Authorization": "Bearer YOUR_BITLY_ACCESS_TOKEN", "Content-Type": "application/json"},
                "body": '{"long_url": "{{url}}"}',
                "docs": "https://dev.bitly.com/api-reference/#createBitlink",
            },
            {
                "id": "qrserver_generate_qr", "name": "QR Code — Generate (no key needed)",
                "method": "GET", "url": "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data={{text}}",
                "headers": {}, "body": "",
                "docs": "https://goqr.me/api/doc/create-qr-code/",
            },
            {
                "id": "openweather_current", "name": "OpenWeatherMap — Current Weather",
                "method": "GET", "url": "https://api.openweathermap.org/data/2.5/weather?q={{city}}&appid=YOUR_OPENWEATHER_API_KEY",
                "headers": {}, "body": "",
                "docs": "https://openweathermap.org/current",
            },
            {
                "id": "exchangerate_latest", "name": "Currency — Latest Exchange Rates",
                "method": "GET", "url": "https://api.exchangerate-api.com/v4/latest/{{base_currency}}",
                "headers": {}, "body": "",
                "docs": "https://www.exchangerate-api.com/docs/free",
            },
            {
                "id": "ipapi_geolocate", "name": "IP Geolocation — Lookup IP",
                "method": "GET", "url": "https://ipapi.co/{{ip_address}}/json/",
                "headers": {}, "body": "",
                "docs": "https://ipapi.co/api/",
            },
        ],
    },
]


def get_integration_catalog():
    """Returns the catalog as-is — a list of {category, icon, items}."""
    return CATALOG


def count_integrations():
    return sum(len(cat["items"]) for cat in CATALOG)


def find_integration(item_id):
    for cat in CATALOG:
        for item in cat["items"]:
            if item["id"] == item_id:
                return item
    return None
